import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"

import styled, { ThemeProvider, keyframes } from "styled-components"

import { Search } from "../components/Search"
import { useState } from "react"
import fetchAPI from "../lib/fetchAPI"

const theme = {
  bg: "#EFF5F5",
  text: "#497174",
  border: "#D6E4E5",
  error: "#EB6440",
}

const inter = Inter({ subsets: ["latin"] })

type HomeProps = {
  breeds: []
}

type BreedProps = {
  name: string
  description: string
  id: string
}

export default function Home({ breeds }: HomeProps) {
  const [results, setResults] = useState([...breeds])
  return (
    <>
      <Head>
        <title>All dogs breeds - petmate.mobi</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Wrapper>
          <Header>
            <Search onResults={setResults} />
          </Header>
          <Results>
            {results.map((b: BreedProps, i) => (
              <BreedContainer key={i}>
                <Img
                  alt={b.name}
                  src={`https://res.cloudinary.com/kondosoft-com/image/upload/v1671210157/petmate/breeds-api/${b.id}/01.png`}
                  width="200"
                  height="200"
                />
                <Title>{b.name}</Title>
                <Description>{b.description}</Description>
              </BreedContainer>
            ))}
            {results.length === 0 && (
              <h3>No encontramos ninguna raza con ese nombre</h3>
            )}
          </Results>
        </Wrapper>
      </ThemeProvider>
    </>
  )
}

export async function getServerSideProps() {
  const res = await fetch("https://breeds-api.petmate.mobi/api/breeds")
  const data = await res.json()
  const breeds = data

  return {
    props: {
      breeds,
    },
  }
}

const Wrapper = styled.div`
  background-color: ${({ theme }) => theme.bg};
  color: ${({ theme }) => theme.text};
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: flex-start;
  align-items: center;
  flex: 1;
  min-width: 100%;
  margin: 0;
  padding: 0;
`

const Header = styled.div`
  width: 70%;
  text-align: center;
  padding: 10px;
`

const Results = styled.div`
  width: 70%;
`

const BreedContainer = styled.div`
  display: inline-block;
  width: 100%;
  padding: 10px;
  margin: 10px auto;
`

const Img = styled.img`
  margin: 0 20px 0 0;
  float: left;
  border-radius: 5px;
`

const Title = styled.h3`
  color: ${({ theme }) => theme.text};
`

const Description = styled.p`
  color: ${({ theme }) => theme.text};
`
